services:

  mysql:
    image: mysql:8.0
    container_name: interntrack-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interntrack
    ports:
      - "3307:3306"
    volumes:
      - interntrack_mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: interntrack-backend
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/interntrack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: InternTrackSuperSecretKeyForJwtAuthentication2026Secure
      JWT_EXPIRATION: 86400000

volumes:
  interntrack_mysql_data: